# Generated by Django 4.2.27 on 2026-01-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='体检人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('time_slot', models.CharField(help_text='如: 08:00-10:00', max_length=20, verbose_name='预约时段')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '已确认'), (2, '已完成'), (3, '已取消'), (4, '已拒绝')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package', verbose_name='套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '体检预约',
                'verbose_name_plural': '体检预约',
                'db_table': 'appointment',
                'ordering': ['-created_at'],
            },
        ),
    ]
