# Generated by Django 4.2.27 on 2026-01-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '套餐分类',
                'verbose_name_plural': '套餐分类',
                'db_table': 'category',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='套餐描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='封面图')),
                ('items', models.TextField(blank=True, default='', help_text='JSON格式存储项目列表', verbose_name='包含项目')),
                ('suitable_for', models.CharField(blank=True, default='', max_length=200, verbose_name='适用人群')),
                ('notice', models.TextField(blank=True, default='', verbose_name='注意事项')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '体检套餐',
                'verbose_name_plural': '体检套餐',
                'db_table': 'package',
                'ordering': ['-is_hot', '-sales_count', '-created_at'],
            },
        ),
    ]
