# Generated by Django 4.2.27 on 2026-01-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='结果摘要')),
                ('file_url', models.CharField(blank=True, default='', max_length=255, verbose_name='报告文件URL')),
                ('doctor', models.CharField(blank=True, default='', max_length=50, verbose_name='报告医生')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='报告日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '体检报告',
                'verbose_name_plural': '体检报告',
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
    ]
